# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('item_title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('item_abstract', models.TextField(verbose_name='Item abstract')),
                ('item_label', models.CharField(choices=[('early primary level', 'Early primary level'), ('primary level', 'Primary level'), ('Middle school level', 'Middle school level'), ('highschool level', 'Highschool level'), ('intermediate level', 'Intermediate level')], max_length=255, verbose_name='Education Level')),
                ('item_interactivity', models.CharField(choices=[('interactive', 'Interactive'), ('noninteractive', 'Non interactive')], max_length=15, verbose_name='Item Interactive')),
                ('item_language', models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English')], max_length=255, verbose_name='Item Language')),
                ('item_citation', models.CharField(blank=True, max_length=255, verbose_name='Citation')),
                ('item_reference_link', models.URLField(blank=True, verbose_name='Item reference link')),
                ('item_additional_node', models.TextField(blank=True, verbose_name='Additional Note')),
                ('item_sponsors', models.CharField(blank=True, max_length=255, verbose_name='Sponsors')),
                ('item_description', models.TextField(verbose_name='Item description')),
                ('item_license_type', models.CharField(choices=[('creative commons', 'Creative Commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache License 2.0'), ('creative commons', 'Creative Commons'), ('mit license', 'MIT License')], max_length=255, verbose_name='Item license type')),
                ('item_custom_license', models.TextField(blank=True, verbose_name='Item custom license')),
                ('item_years_of_available', models.DateField(blank=True, verbose_name='Years of available')),
                ('item_date_of_issue', models.DateField(blank=True, verbose_name='Item date of issue')),
                ('item_identifier_type', models.CharField(choices=[('issn', 'ISSN'), ('ismn', 'ISMN'), ('govt doc', "Gov't Doc"), ('uri', 'URI'), ('isbn', 'ISBN')], max_length=255, verbose_name='Item identifier type')),
                ('item_place_of_publication', models.CharField(blank=True, max_length=255, verbose_name='Place of publication')),
                ('document_type', models.CharField(choices=[('book', 'Book'), ('working paper', 'Working paper'), ('thesis', 'Thesis'), ('journal paper', 'Journal paper'), ('technical report', 'Technical report'), ('article', 'Article')], max_length=40, verbose_name='Document type')),
                ('document_file_type', models.CharField(choices=[('ppt', 'PPT'), ('doc', 'Doc'), ('docx', 'Docx'), ('pdf', 'PDF'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('epub', 'Epub'), ('rtf', 'Rtf'), ('mobi', 'Mobi')], max_length=23, verbose_name='Document file type')),
                ('document_total_pages', models.PositiveIntegerField(verbose_name='Document pages')),
            ],
            options={
                'ordering': ('item_title',),
            },
        ),
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentIllustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('series_name', models.CharField(max_length=255, verbose_name='Series name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_author',
            field=models.ManyToManyField(to='document.DocumentAuthor', verbose_name='Document Author'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_editor',
            field=models.ManyToManyField(to='document.DocumentEditor', verbose_name='Document Editor'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_illustrator',
            field=models.ManyToManyField(to='document.DocumentIllustrator', verbose_name='Document Illustrator'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentSeries', verbose_name='Document series'),
        ),
    ]
