# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='item_Collection',
            field=models.ManyToManyField(to='collection.Collection', verbose_name='Collection List'),
        ),
    ]
