# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='featured',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_interactivity',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('NA', 'Not applicable')], max_length=15, verbose_name='Interactive'),
        ),
        migrations.AlterField(
            model_name='document',
            name='license_type',
            field=models.CharField(choices=[('creative commons', 'Creative commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache license 2.0'), ('creative commons', 'Creative commons'), ('mit license', 'MIT License'), ('custom license', 'Custom License'), ('na', 'Not available')], max_length=255, verbose_name='License type'),
        ),
    ]
