# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20170918_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_category',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
