# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20180220_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher', verbose_name='Publisher name'),
        ),
    ]
