# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_document_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpublishedDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('document.document',),
        ),
    ]
