# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_unpublisheddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfileupload',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='File name'),
        ),
    ]
