# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20180221_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_interactivity',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('NA', 'Not applicable')], default='NA', max_length=15, verbose_name='Interactive'),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='core.Keyword', verbose_name='Select list of keywords'),
        ),
        migrations.AlterField(
            model_name='document',
            name='license_type',
            field=models.CharField(blank=True, choices=[('creative commons', 'Creative commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache license 2.0'), ('creative commons', 'Creative commons'), ('mit license', 'MIT License'), ('custom license', 'Custom License'), ('na', 'Not available')], max_length=255, verbose_name='License type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='maximum size of thumbnail should be 255px by 300px', max_length=255, upload_to='uploads/thumbnails/document/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='documentidentifier',
            name='identifier_type',
            field=models.CharField(blank=True, choices=[('issn', 'ISSN'), ('ismn', 'ISMN'), ('govt_doc', "Gov't Doc"), ('uri', 'URI'), ('isbn', 'ISBN')], max_length=8, verbose_name='Identifier Type'),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
