# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import pustakalaya_apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20180306_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_total_page',
            field=models.CharField(blank=True, default=0, max_length=4, validators=[pustakalaya_apps.core.validators.validate_number], verbose_name='Total Pages'),
        ),
    ]
