# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_auto_20180319_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.ManyToManyField(blank=True, related_name='publisher', to='core.Publisher', verbose_name='Publisher name'),
        ),
    ]
