# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract/Summary')),
                ('additional_note', models.TextField(blank=True, verbose_name='Additional Note')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('license_type', models.CharField(choices=[('creative commons', 'Creative commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache license 2.0'), ('creative commons', 'Creative commons'), ('mit license', 'MIT License'), ('custom license', 'Custom License'), ('na', 'Not available')], max_length=255, verbose_name='License type')),
                ('custom_license', models.TextField(blank=True, verbose_name='Rights')),
                ('year_of_available', models.DateField(blank=True, null=True, verbose_name='Year of available')),
                ('publication_year', models.DateField(blank=True, null=True, verbose_name='Publication year')),
                ('place_of_publication', models.CharField(blank=True, max_length=255, verbose_name='Place of publication')),
                ('volume', models.CharField(blank=True, default='', max_length=254)),
                ('edition', models.CharField(blank=True, default='', max_length=254)),
                ('featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Featured')),
                ('published', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='published')),
                ('type', models.CharField(default='video', editable=False, max_length=4)),
                ('video_certificate_license', models.CharField(blank=True, max_length=255, verbose_name='Certification')),
                ('age', models.CharField(blank=True, max_length=255, verbose_name='Age group')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='uploads/thumbnails/video/%Y/%m/%d')),
                ('video_running_time', models.CharField(blank=True, default='0', max_length=3, verbose_name='Running time in minutes')),
                ('collections', models.ManyToManyField(to='collection.Collection', verbose_name='Add this video to these collection')),
                ('education_levels', models.ManyToManyField(to='core.EducationLevel', verbose_name='Education Level')),
                ('keywords', models.ManyToManyField(to='core.Keyword', verbose_name='Keywords')),
                ('languages', models.ManyToManyField(to='core.Language', verbose_name='Languages')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publisher', verbose_name='Publisher')),
                ('sponsors', models.ManyToManyField(blank=True, null=True, to='core.Sponsor', verbose_name='Sponsor')),
                ('video_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='core.Biography', verbose_name='Director')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
                ('upload', models.FileField(max_length=255, upload_to='uploads/videos/%Y/%m/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre name')),
                ('genre_description', models.TextField(verbose_name='Genre description')),
            ],
            options={
                'db_table': 'video_genre',
            },
        ),
        migrations.CreateModel(
            name='VideoLinkInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('link_name', models.URLField(verbose_name='Link URL')),
                ('link_description', models.CharField(max_length=500, verbose_name='Link Description')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('series_name', models.CharField(max_length=255, verbose_name='Series name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoGenre', verbose_name='Video Genre'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_producers',
            field=models.ManyToManyField(blank=True, null=True, related_name='producers', to='core.Biography', verbose_name='Producer'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoSeries', verbose_name='Video series'),
        ),
    ]
