# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('education_level', models.CharField(choices=[('early primary level', 'Early primary level'), ('primary level', 'Primary level'), ('Middle school level', 'Middle school level'), ('highschool level', 'Highschool level'), ('intermediate level', 'Intermediate level')], max_length=255, verbose_name='Education Level')),
                ('language', models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English')], max_length=255, verbose_name='Language')),
                ('citation', models.CharField(blank=True, max_length=255, verbose_name='Citation')),
                ('reference_link', models.URLField(blank=True, verbose_name='Reference link')),
                ('additional_note', models.TextField(blank=True, verbose_name='Additional Note')),
                ('description', models.TextField(verbose_name='Description')),
                ('license_type', models.CharField(choices=[('creative commons', 'Creative Commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache License 2.0'), ('creative commons', 'Creative Commons'), ('mit license', 'MIT License')], max_length=255, verbose_name='License type')),
                ('custom_license', models.TextField(blank=True, verbose_name='Custom license')),
                ('year_of_available', models.DateField(blank=True, null=True, verbose_name='Year of available')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Date of issue')),
                ('place_of_publication', models.CharField(blank=True, max_length=255, verbose_name='Place of publication')),
                ('type', models.CharField(default='video', editable=False, max_length=4)),
                ('video_certificate_license', models.CharField(max_length=255, verbose_name='Certificate license name')),
                ('video_thumbnail', models.ImageField(max_length=255, upload_to='uploads/thumbnails/video/%Y/%m/%d')),
                ('video_running_time', models.CharField(max_length=3, verbose_name='Running time in minutes')),
                ('collection', models.ManyToManyField(to='collection.Collection', verbose_name='Add this audio to these collection')),
                ('keywords', models.ManyToManyField(to='core.Keyword', verbose_name='Keywords')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publisher', verbose_name='Publisher')),
                ('sponsors', models.ManyToManyField(to='core.Sponsor', verbose_name='Sponsor')),
                ('video_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Video Category')),
                ('video_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='core.Biography', verbose_name='Director')),
                ('video_producers', models.ManyToManyField(related_name='producers', to='core.Biography', verbose_name='Producer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
                ('upload', models.FileField(max_length=255, upload_to='uploads/videos/%Y/%m/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('series_name', models.CharField(max_length=255, verbose_name='Series name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoSeries', verbose_name='Video series'),
        ),
    ]
