# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('video', '0002_auto_20170918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='collection',
            field=models.ManyToManyField(to='collection.Collection', verbose_name='Add this audio to these collection'),
        ),
    ]
