# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180220_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='core.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='video',
            name='license_type',
            field=models.CharField(blank=True, choices=[('creative commons', 'Creative commons'), ('copyright retained', 'Copyright retained'), ('apache License 2.0', 'Apache license 2.0'), ('creative commons', 'Creative commons'), ('mit license', 'MIT License'), ('custom license', 'Custom License'), ('na', 'Not available')], max_length=255, verbose_name='License type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, upload_to='uploads/thumbnails/video/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='videoseries',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
