# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20180306_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='collection.Collection', verbose_name='Add this video to these collection'),
        ),
        migrations.AlterField(
            model_name='video',
            name='education_levels',
            field=models.ManyToManyField(blank=True, null=True, to='core.EducationLevel', verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='core.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='video',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='core.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='video',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher', verbose_name='Publisher'),
        ),
    ]
