# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20180312_1025'),
        ('video', '0007_auto_20180309_1455'),
    ]

    operations = [
    ]
