# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20180313_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collections',
            field=models.ManyToManyField(blank=True, to='collection.Collection', verbose_name='Add this video to these collection'),
        ),
        migrations.AlterField(
            model_name='video',
            name='education_levels',
            field=models.ManyToManyField(blank=True, to='core.EducationLevel', verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='core.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='video',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='core.Sponsor', verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_producers',
            field=models.ManyToManyField(blank=True, related_name='producers', to='core.Biography', verbose_name='Producer'),
        ),
    ]
