# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180314_1648'),
        ('video', '0012_auto_20180319_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='publisher',
        ),
        migrations.AddField(
            model_name='video',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='core.Publisher', verbose_name='Publisher'),
        ),
    ]
