# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('description', models.TextField(verbose_name='Description')),
                ('dob', models.DateField(blank=True, verbose_name='Date of birth')),
                ('pen_name', models.CharField(max_length=255, verbose_name='Pen name')),
                ('address', models.TextField(verbose_name='Address')),
                ('genre', models.TextField(max_length=100, verbose_name='Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category name')),
                ('category_description', models.TextField(verbose_name='Category description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
                ('keyword_description', models.TextField(verbose_name='Keyword description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('publisher_name', models.CharField(max_length=255, verbose_name='Publisher name')),
                ('publisher_description', models.CharField(max_length=255, verbose_name='Publisher description')),
            ],
            options={
                'ordering': ('publisher_name',),
            },
        ),
        migrations.AddField(
            model_name='biography',
            name='keywords',
            field=models.ManyToManyField(to='core.Keyword', verbose_name='Search Keywords'),
        ),
    ]
