# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180305_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biography',
            name='death_of_death',
        ),
        migrations.AddField(
            model_name='biography',
            name='date_of_death',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Date of death'),
        ),
    ]
