# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180305_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='dob',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Date of birth'),
        ),
    ]
