# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180305_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='core.Keyword', verbose_name='Search Keywords'),
        ),
    ]
