# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180306_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Enter author name'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
    ]
