# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180306_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Author'),
        ),
    ]
