# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180307_0926'),
        ('core', '0008_auto_20180307_1007'),
    ]

    operations = [
    ]
