# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180307_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_description',
            field=models.TextField(blank=True, null=True, verbose_name='Publisher description'),
        ),
    ]
