# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180312_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.TextField(blank=True, max_length=50, null=True, unique=True, verbose_name='License')),
            ],
            options={
                'db_table': 'tbl_license',
            },
        ),
    ]
