# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180312_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='license',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='License'),
            preserve_default=False,
        ),
    ]
