# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180312_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='license',
            field=models.CharField(max_length=50, verbose_name='License'),
        ),
    ]
