# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180313_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=30, unique=True, verbose_name='Language'),
        ),
    ]
