# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180314_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level',
            field=models.CharField(choices=[('Basic school', 'Basic school'), ('Early grade reading', 'Early grade reading'), ('Intermediate level', 'Intermediate level'), ('Middle school', 'Middle school'), ('Primary school', 'Primary school'), ('Secondary school', 'Secondary school'), ('University level', 'University level')], max_length=255, unique=True, verbose_name='Education Level'),
        ),
    ]
