# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('collection_name', models.CharField(max_length=255, verbose_name='Collection name')),
                ('collection_description', models.CharField(max_length=255, verbose_name='Collection description')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community', verbose_name='Community')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
    ]
