# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('community_name', models.CharField(choices=[('literatures and arts', 'Literature and arts'), ('course materials', 'Course materials'), ('teaching materials', 'Teaching materials'), ('reference materials', 'Reference materials'), ('other educational materials', 'Other educational materials'), ('newspaper and  magazines', 'newspaper and magazines')], max_length=255, verbose_name='Community')),
                ('collection_name', models.CharField(max_length=255, unique=True, verbose_name='Collection name')),
                ('collection_description', models.TextField(verbose_name='Collection description')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
    ]
