# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_description',
            field=models.TextField(verbose_name='Collection description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Collection name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='community_name',
            field=models.CharField(choices=[('literatures and arts', 'Literature and arts'), ('course materials', 'Course materials'), ('teaching materials', 'Teaching materials'), ('reference materials', 'Reference materials')], max_length=255, verbose_name='Community'),
        ),
    ]
