# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='community_name',
            field=models.CharField(choices=[('literatures and arts', 'Literature and arts'), ('course materials', 'Course materials'), ('teaching materials', 'Teaching materials'), ('reference materials', 'Reference materials'), ('other educational materials', 'Other educational materials'), ('newspaper and magazines', 'newspaper and magazines')], max_length=255, verbose_name='Community'),
        ),
    ]
