# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180213_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_description',
            field=models.TextField(blank=True, verbose_name='Collection description'),
        ),
    ]
