# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180213_1417'),
        ('collection', '0002_auto_20180214_1215'),
    ]

    operations = [
    ]
