# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_merge_20180226_1211'),
        ('collection', '0003_auto_20180307_1423'),
    ]

    operations = [
    ]
