# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('community_name', models.CharField(max_length=255, verbose_name='Community name')),
                ('community_description', models.CharField(max_length=255, verbose_name='Community description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
