# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('community_name', models.CharField(max_length=255, unique=True, verbose_name='Community name')),
                ('community_description', models.CharField(max_length=255, verbose_name='Community description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
