# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='collection_description',
            new_name='community_description',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='collection_name',
            new_name='community_name',
        ),
    ]
