#!/bin/bash
# Creates Cron Job which backups DB in Docker everyday at 22:00 host time
croncmd_backup="docker exec -it postgres_01 bash -c '/script/autopgsqlbackup'"
cronjob_backup="*/5 * * * * $croncmd_backup"

if [[ $# -eq 0 ]] ; then
    echo -e 'Please provide one of the arguments (example: ./postgres_backup.sh add-cron-db-backup):
    1 > add-cron-db-backup
    2 > remove-cron-db-backup'

elif [[ $1 == add-cron-db-backup ]]; then
    ( crontab -l | grep -v -F "$croncmd_backup" ; echo "$cronjob_backup" ) | crontab -
    echo "==>>> Backup task added to Local (not container) Cron"

elif [[ $1 == remove-cron-db-backup ]]; then
    ( crontab -l | grep -v -F "$croncmd_backup" ) | crontab -
    echo "==>>> Backup task removed from Cron"

fi

