# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20180305_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='publication_year_on_text',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Publication year'),
        ),
        migrations.AddField(
            model_name='audio',
            name='year_of_available_on_text',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Year of available'),
        ),
    ]
