# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20180307_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_types',
            field=models.ManyToManyField(blank=True, null=True, to='audio.AudioType', verbose_name='Audio types'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='collection.Collection', verbose_name='Add this audio to these collection'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='core.Language', verbose_name='Languages'),
        ),
    ]
