# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_auto_20180312_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LicenseType', verbose_name='license'),
        ),
    ]
