# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0013_auto_20180319_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofileupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='File name'),
        ),
    ]
